# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openphase/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openphase/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from openphase.v1 import spat_pb2 as openphase_dot_v1_dot_spat__pb2
from openphase.v1 import ihr_events_pb2 as openphase_dot_v1_dot_ihr__events__pb2
from openphase.v1 import health_pb2 as openphase_dot_v1_dot_health__pb2
from openphase.v1 import security_pb2 as openphase_dot_v1_dot_security__pb2
from openphase.v1 import discovery_pb2 as openphase_dot_v1_dot_discovery__pb2
from openphase.v1 import faults_pb2 as openphase_dot_v1_dot_faults__pb2
from openphase.v1 import ntcip_pb2 as openphase_dot_v1_dot_ntcip__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19openphase/v1/common.proto\x12\x0copenphase.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17openphase/v1/spat.proto\x1a\x1dopenphase/v1/ihr_events.proto\x1a\x19openphase/v1/health.proto\x1a\x1bopenphase/v1/security.proto\x1a\x1copenphase/v1/discovery.proto\x1a\x19openphase/v1/faults.proto\x1a\x18openphase/v1/ntcip.proto\"\x8b\x04\n\x12IntersectionUpdate\x12\x17\n\x0fintersection_id\x18\x01 \x01(\t\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x04spat\x18\x03 \x01(\x0b\x32\x18.openphase.v1.SpatUpdateH\x00\x12)\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x18.openphase.v1.AtspmEventH\x00\x12/\n\x08security\x18\x05 \x01(\x0b\x32\x1b.openphase.v1.SecurityAlertH\x00\x12\x32\n\tdiscovery\x18\x06 \x01(\x0b\x32\x1d.openphase.v1.DiscoveryPacketH\x00\x12,\n\x06health\x18\x07 \x01(\x0b\x32\x1a.openphase.v1.DeviceHealthH\x00\x12,\n\x05\x66\x61ult\x18\x08 \x01(\x0b\x32\x1b.openphase.v1.FaultSnapshotH\x00\x12\x30\n\x06\x63onfig\x18\t \x01(\x0b\x32\x1e.openphase.v1.ControllerConfigH\x00\x12\x30\n\x06status\x18\n \x01(\x0b\x32\x1e.openphase.v1.ControllerStatusH\x00\x12/\n\x0c\x63lock_source\x18\x0f \x01(\x0e\x32\x19.openphase.v1.ClockSourceB\t\n\x07payload\"e\n\x17IntersectionUpdateBatch\x12\x17\n\x0fintersection_id\x18\x01 \x01(\t\x12\x31\n\x07updates\x18\x02 \x03(\x0b\x32 .openphase.v1.IntersectionUpdate\"\xa4\x01\n\x11\x43ompactEventBatch\x12\x17\n\x0fintersection_id\x18\x01 \x01(\t\x12\x19\n\x11\x62\x61se_timestamp_ns\x18\x02 \x01(\x03\x12/\n\x0c\x63lock_source\x18\x03 \x01(\x0e\x32\x19.openphase.v1.ClockSource\x12*\n\x06\x65vents\x18\x04 \x03(\x0b\x32\x1a.openphase.v1.CompactEvent*\x86\x01\n\x0b\x43lockSource\x12\x1c\n\x18\x43LOCK_SOURCE_UNSPECIFIED\x10\x00\x12\r\n\tCLOCK_PTP\x10\x01\x12\r\n\tCLOCK_NTP\x10\x02\x12\r\n\tCLOCK_GPS\x10\x03\x12\x14\n\x10\x43LOCK_POWER_LINE\x10\x04\x12\x16\n\x12\x43LOCK_FREE_RUNNING\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openphase.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLOCKSOURCE']._serialized_start=1068
  _globals['_CLOCKSOURCE']._serialized_end=1202
  _globals['_INTERSECTIONUPDATE']._serialized_start=272
  _globals['_INTERSECTIONUPDATE']._serialized_end=795
  _globals['_INTERSECTIONUPDATEBATCH']._serialized_start=797
  _globals['_INTERSECTIONUPDATEBATCH']._serialized_end=898
  _globals['_COMPACTEVENTBATCH']._serialized_start=901
  _globals['_COMPACTEVENTBATCH']._serialized_end=1065
# @@protoc_insertion_point(module_scope)
