# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openphase/v1/discovery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openphase/v1/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenphase/v1/discovery.proto\x12\x0copenphase.v1\"\xe4\x01\n\x0f\x44iscoveryPacket\x12\x14\n\x0csdlc_address\x18\x01 \x01(\r\x12\x12\n\nbyte_index\x18\x02 \x01(\r\x12\x11\n\tbit_index\x18\x03 \x01(\r\x12\x11\n\told_state\x18\x04 \x01(\x08\x12\x11\n\tnew_state\x18\x05 \x01(\x08\x12\x15\n\rframe_context\x18\x06 \x01(\x0c\x12*\n\tdirection\x18\x07 \x01(\x0e\x32\x17.openphase.v1.Direction\x12\x17\n\x0fsuspected_event\x18\n \x01(\t\x12\x12\n\nconfidence\x18\x0b \x01(\x02*6\n\tDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x06\n\x02TX\x10\x01\x12\x06\n\x02RX\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openphase.v1.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIRECTION']._serialized_start=277
  _globals['_DIRECTION']._serialized_end=331
  _globals['_DISCOVERYPACKET']._serialized_start=47
  _globals['_DISCOVERYPACKET']._serialized_end=275
# @@protoc_insertion_point(module_scope)
