# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openphase/v1/faults.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openphase/v1/faults.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from openphase.v1 import ihr_events_pb2 as openphase_dot_v1_dot_ihr__events__pb2
from openphase.v1 import spat_pb2 as openphase_dot_v1_dot_spat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19openphase/v1/faults.proto\x12\x0copenphase.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dopenphase/v1/ihr_events.proto\x1a\x17openphase/v1/spat.proto\"\xcf\x03\n\rFaultSnapshot\x12+\n\nfault_type\x18\x01 \x01(\x0e\x32\x17.openphase.v1.FaultType\x12.\n\nfault_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x19history_base_timestamp_ns\x18\x0e \x01(\x03\x12\x31\n\rrecent_events\x18\x03 \x03(\x0b\x32\x1a.openphase.v1.CompactEvent\x12\x31\n\x0cphase_states\x18\x04 \x03(\x0b\x32\x1b.openphase.v1.MovementState\x12\x19\n\x11\x66\x61ult_description\x18\n \x01(\t\x12\x17\n\x0fmmu_status_code\x18\x0b \x01(\r\x12\x1a\n\x12mmu_fault_register\x18\x0c \x01(\x0c\x12\x18\n\x10\x63onflict_bitmask\x18\r \x01(\x0c\x12\x1a\n\x12\x61\x63tive_timing_plan\x18\x14 \x01(\r\x12\x39\n\x11\x63oordination_mode\x18\x15 \x01(\x0e\x32\x1e.openphase.v1.CoordinationMode\x12\x17\n\x0fsdlc_bus_health\x18\x16 \x01(\x02*\xb8\x01\n\tFaultType\x12\x1a\n\x16\x46\x41ULT_TYPE_UNSPECIFIED\x10\x00\x12\x18\n\x14MMU_CONFLICT_MONITOR\x10\x01\x12\x10\n\x0cSDLC_TIMEOUT\x10\x02\x12\x14\n\x10WATCHDOG_TIMEOUT\x10\x03\x12\x11\n\rSECURITY_VETO\x10\x04\x12\x11\n\rDECODER_ERROR\x10\x05\x12\x13\n\x0f\x42UFFER_OVERFLOW\x10\x06\x12\x12\n\x0eHARDWARE_FAULT\x10\x07*\x96\x01\n\x10\x43oordinationMode\x12!\n\x1d\x43OORDINATION_MODE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x43OORDINATION_FREE\x10\x01\x12\x16\n\x12\x43OORDINATION_COORD\x10\x02\x12\x18\n\x14\x43OORDINATION_PREEMPT\x10\x03\x12\x16\n\x12\x43OORDINATION_FLASH\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openphase.v1.faults_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FAULTTYPE']._serialized_start=599
  _globals['_FAULTTYPE']._serialized_end=783
  _globals['_COORDINATIONMODE']._serialized_start=786
  _globals['_COORDINATIONMODE']._serialized_end=936
  _globals['_FAULTSNAPSHOT']._serialized_start=133
  _globals['_FAULTSNAPSHOT']._serialized_end=596
# @@protoc_insertion_point(module_scope)
