# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openphase/v1/health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openphase/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19openphase/v1/health.proto\x12\x0copenphase.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x05\n\x0c\x44\x65viceHealth\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.openphase.v1.HealthStatus\x12\x10\n\x08uptime_s\x18\x02 \x01(\x04\x12\x16\n\x0e\x65vents_decoded\x18\n \x01(\x04\x12\x18\n\x10\x65vents_delivered\x18\x0b \x01(\x04\x12\x16\n\x0e\x65vents_pending\x18\x0c \x01(\x04\x12\x16\n\x0e\x65vents_dropped\x18\r \x01(\x04\x12\x19\n\x11\x64iscovery_packets\x18\x0e \x01(\x04\x12\x12\n\ncpu_temp_c\x18\x14 \x01(\x02\x12\x17\n\x0fmemory_used_pct\x18\x15 \x01(\x02\x12\x17\n\x0f\x62uffer_used_pct\x18\x16 \x01(\x02\x12\x15\n\rdisk_used_pct\x18\x17 \x01(\x02\x12\x16\n\x0e\x63\x61\x62inet_temp_c\x18\x19 \x01(\x02\x12\x19\n\x11\x63\x61\x62inet_door_open\x18\x1a \x01(\x08\x12\x32\n\x0elast_door_open\x18\x1b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x14sdlc_frames_received\x18\x1e \x01(\x04\x12\x17\n\x0fsdlc_crc_errors\x18\x1f \x01(\x04\x12\x1a\n\x12sdlc_frame_rate_hz\x18  \x01(\x02\x12\x1b\n\x13\x63\x61n_frames_received\x18# \x01(\x04\x12\x12\n\ncan_errors\x18$ \x01(\x04\x12\x19\n\x11\x63\x61n_frame_rate_hz\x18% \x01(\x02\x12\x16\n\x0enats_connected\x18( \x01(\x08\x12\x1b\n\x13nats_publish_errors\x18) \x01(\x04\x12 \n\x18\x61\x63tive_network_interface\x18* \x01(\t\x12\x18\n\x10\x66irmware_version\x18\x32 \x01(\t\x12\x17\n\x0f\x64\x65\x63oder_version\x18\x33 \x01(\t\x12\x17\n\x0fmapping_version\x18\x34 \x01(\t\x12\x19\n\x11hardware_revision\x18\x35 \x01(\t*c\n\x0cHealthStatus\x12\x1d\n\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\r\n\tHEALTH_OK\x10\x01\x12\x13\n\x0fHEALTH_DEGRADED\x10\x02\x12\x10\n\x0cHEALTH_ERROR\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openphase.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHSTATUS']._serialized_start=825
  _globals['_HEALTHSTATUS']._serialized_end=924
  _globals['_DEVICEHEALTH']._serialized_start=77
  _globals['_DEVICEHEALTH']._serialized_end=823
# @@protoc_insertion_point(module_scope)
