# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openphase/v1/ingestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openphase/v1/ingestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openphase.v1 import common_pb2 as openphase_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1copenphase/v1/ingestion.proto\x12\x0copenphase.v1\x1a\x19openphase/v1/common.proto\"4\n\nPublishAck\x12\x17\n\x0f\x65vents_accepted\x18\x01 \x01(\r\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xf8\x01\n\x10IngestionService\x12K\n\rPublishUpdate\x12 .openphase.v1.IntersectionUpdate\x1a\x18.openphase.v1.PublishAck\x12I\n\x0cPublishBatch\x12\x1f.openphase.v1.CompactEventBatch\x1a\x18.openphase.v1.PublishAck\x12L\n\rStreamBatches\x12\x1f.openphase.v1.CompactEventBatch\x1a\x18.openphase.v1.PublishAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openphase.v1.ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHACK']._serialized_start=73
  _globals['_PUBLISHACK']._serialized_end=125
  _globals['_INGESTIONSERVICE']._serialized_start=128
  _globals['_INGESTIONSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
