# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from openphase.v1 import common_pb2 as openphase_dot_v1_dot_common__pb2
from openphase.v1 import ingestion_pb2 as openphase_dot_v1_dot_ingestion__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in openphase/v1/ingestion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestionServiceStub(object):
    """gRPC service for pushing OpenPhase telemetry to an ingestion server.

    Transport-agnostic: the same `IntersectionUpdate` and `CompactEventBatch`
    messages used over NATS/MQTT travel here unchanged.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishUpdate = channel.unary_unary(
                '/openphase.v1.IngestionService/PublishUpdate',
                request_serializer=openphase_dot_v1_dot_common__pb2.IntersectionUpdate.SerializeToString,
                response_deserializer=openphase_dot_v1_dot_ingestion__pb2.PublishAck.FromString,
                _registered_method=True)
        self.PublishBatch = channel.unary_unary(
                '/openphase.v1.IngestionService/PublishBatch',
                request_serializer=openphase_dot_v1_dot_common__pb2.CompactEventBatch.SerializeToString,
                response_deserializer=openphase_dot_v1_dot_ingestion__pb2.PublishAck.FromString,
                _registered_method=True)
        self.StreamBatches = channel.stream_unary(
                '/openphase.v1.IngestionService/StreamBatches',
                request_serializer=openphase_dot_v1_dot_common__pb2.CompactEventBatch.SerializeToString,
                response_deserializer=openphase_dot_v1_dot_ingestion__pb2.PublishAck.FromString,
                _registered_method=True)


class IngestionServiceServicer(object):
    """gRPC service for pushing OpenPhase telemetry to an ingestion server.

    Transport-agnostic: the same `IntersectionUpdate` and `CompactEventBatch`
    messages used over NATS/MQTT travel here unchanged.
    """

    def PublishUpdate(self, request, context):
        """Push a single multi-payload update (SPaT, IHR event, health, security,
        discovery, fault, controller config/status). Use for low-volume or
        mixed-payload publishing where each message stands alone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishBatch(self, request, context):
        """Push a single batch of IHR events with delta-encoded timestamps.
        Use for medium-volume periodic pushes (e.g., every few seconds).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBatches(self, request_iterator, context):
        """Long-lived client-streaming push of IHR event batches. Devices keep
        the stream open and push batches as they're produced. Server returns
        a single PublishAck when the stream closes (cumulative count). Use
        for high-volume continuous telemetry (the common ATSPM streaming case).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishUpdate,
                    request_deserializer=openphase_dot_v1_dot_common__pb2.IntersectionUpdate.FromString,
                    response_serializer=openphase_dot_v1_dot_ingestion__pb2.PublishAck.SerializeToString,
            ),
            'PublishBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishBatch,
                    request_deserializer=openphase_dot_v1_dot_common__pb2.CompactEventBatch.FromString,
                    response_serializer=openphase_dot_v1_dot_ingestion__pb2.PublishAck.SerializeToString,
            ),
            'StreamBatches': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamBatches,
                    request_deserializer=openphase_dot_v1_dot_common__pb2.CompactEventBatch.FromString,
                    response_serializer=openphase_dot_v1_dot_ingestion__pb2.PublishAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openphase.v1.IngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openphase.v1.IngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestionService(object):
    """gRPC service for pushing OpenPhase telemetry to an ingestion server.

    Transport-agnostic: the same `IntersectionUpdate` and `CompactEventBatch`
    messages used over NATS/MQTT travel here unchanged.
    """

    @staticmethod
    def PublishUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openphase.v1.IngestionService/PublishUpdate',
            openphase_dot_v1_dot_common__pb2.IntersectionUpdate.SerializeToString,
            openphase_dot_v1_dot_ingestion__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openphase.v1.IngestionService/PublishBatch',
            openphase_dot_v1_dot_common__pb2.CompactEventBatch.SerializeToString,
            openphase_dot_v1_dot_ingestion__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBatches(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/openphase.v1.IngestionService/StreamBatches',
            openphase_dot_v1_dot_common__pb2.CompactEventBatch.SerializeToString,
            openphase_dot_v1_dot_ingestion__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
