# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: openphase/v1/security.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'openphase/v1/security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bopenphase/v1/security.proto\x12\x0copenphase.v1\"\xc6\x01\n\rSecurityAlert\x12\'\n\x05level\x18\x01 \x01(\x0e\x32\x18.openphase.v1.AlertLevel\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x1c\n\x14physical_fingerprint\x18\x04 \x01(\x0c\x12-\n\x0bthreat_type\x18\n \x01(\x0e\x32\x18.openphase.v1.ThreatType\x12\x1a\n\x12\x61ttacker_signature\x18\x0b \x01(\t*N\n\nAlertLevel\x12\x1b\n\x17\x41LERT_LEVEL_UNSPECIFIED\x10\x00\x12\x08\n\x04INFO\x10\x01\x12\x0b\n\x07WARNING\x10\x02\x12\x0c\n\x08\x43RITICAL\x10\x03*\x8e\x01\n\nThreatType\x12\x1b\n\x17THREAT_TYPE_UNSPECIFIED\x10\x00\x12\x10\n\x0cGPS_SPOOFING\x10\x01\x12\x15\n\x11TSP_REPLAY_ATTACK\x10\x02\x12\x11\n\rPREEMPT_SPOOF\x10\x03\x12\x10\n\x0cMMU_CONFLICT\x10\x04\x12\x15\n\x11NETWORK_INTRUSION\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openphase.v1.security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERTLEVEL']._serialized_start=246
  _globals['_ALERTLEVEL']._serialized_end=324
  _globals['_THREATTYPE']._serialized_start=327
  _globals['_THREATTYPE']._serialized_end=469
  _globals['_SECURITYALERT']._serialized_start=46
  _globals['_SECURITYALERT']._serialized_end=244
# @@protoc_insertion_point(module_scope)
